# Site settings
title: François Goybet
description: François Goybet Resume

# User settings
username: François Goybet
user_description: description
user_title: Data Science and Financial Engineering Student
email: francoisgoybet@gmail.com  
github_username:  francois-goybet

exclude: ['package.json', 'src' , 'node_modules']
