# Site settings
title: François Goybet
description: Data Science et Financial Engineering Student
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: François Goybet
user_description: Data Science et Financial Engineering Student
user_title: Data Science et Financial Engineering Student
email: francoisgoybet@gmail.com
github_username:  francois-goybet

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
